### PR TITLE
Fix crash when running with a wheel that doesn't support all the effects

### PR DESCRIPTION
**Pull request by ericblade**
Return DIERR_UNSUPPORTED when attempting to play force feedback effects
that do not exist on the hardware that is plugged in. Prevents crashing
the Unity editor when playing inside the editor, when there is a device
plugged in that does not support the springForce, damperForce, or
constantForce functions.

Also return false from the bool functions for stopping said effects.

Also make sure that all fields in the device struct are initialized to
zero when the device struct is created.

### CODE REVIEW

**Comment by ericblade** [comment]
... should the DLL also be committed here? I am not 100% familiar with how the Unity processes work yet, so I am not sure if that gets built somehow when the source is updated, or no.

**Comment by simonmcm1** [comment]
@ericblade Yes the DLL in Assets/Plugins/DirectInput/x64 should also be committed here, thanks

**Comment by ericblade** [comment]
Thanks, Simon.  Added that.  I'm doing some exploration with the simulator, and the wheel / pedals that I had quickly available to me is ridiculously old, but works fine after this change, and some adjustment to the handling in SteeringWheelInputController.  I'd expect that this change quite likely doesn't affect the operation with the nice new wheels, but I don't have one to test it on.

**Comment by simonmcm1** [comment]
Great, thanks Eric.

We have a limited selection of wheels to test on and they work the same so it's great to have support for older hardware now too.

Out of interest, what were the changes you had to also make to SteeringWheelInputController? Just different input axes?

**Comment by ericblade** [comment]
Yes, since the wheel identifies as a single device, with X for wheel and Y for brake/gas, had to set the wheel and pedalIndex to 0, the axes for pedal to Y, and set the limits for the pedals in the 0-32767 and -1 to -32767 range. 

I have worked up some possible improvements to the device enumeration, using the DirectInput functions that are specifically for driving devices .. but then I discovered that my wheel only reports that it is a game device, not a driving subtype, so I can't test it until I get something newer hopefully next week.

**Comment by ericblade** [comment]
This is actually my first go at writing DirectInput code (a few years late, I suppose, since Microsoft suggests we should all be using XInput now, oh well :) ), or anything involving steering, but I put together something that works like this:

Attempt to enumerate driving devices.  If there are two driving devices attached, follow the existing pattern of "the one that reports force feedback ability is probably a wheel, and the other is pedals".  If there is only one, assume it's probably a wheel with pedals.

If no devices that identify as a driving device are found, but there are two controllers, follow the existing code.  If there is only one controller, assume it's a wheel.

Attempt to enumerate the number of pedal axes, and set the pedal axes appropriately (1 axis = Y, 2 axes = Y/Z, 3 axes = Y/Z/??). If only 1 axis, then use half the range for gas, half the range for brake.  

I'm hoping that more modern devices implement all the correct interfaces, so can be enumerated with high confidence of being able to automatically detect all the operating parameters (including which axis is which function, and what the limits of those axes are), but I suspect that there might still be a wide range of hardware out there in which assumptions have to be made, and manual configuration values provided :-D

**Pull request merged**
